config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tweets#index"
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets= Tweet.includes(:user).page(params[:page]).per(6).order("created_at DESC") 
  end

  def new
    @tweet= Tweet.new
  end

  def create
    @tweets = Tweet.create(tweet_params)
  end
  
  def edit
    @tweet=Tweet.find(params[:id])
  end

  def update
  tweet=Tweet.find(params[:id])
  tweet.update(tweet_params)
  redirect_to tweets_path, notice: 'tweetを編集しました'

 
  end
  def destroy
    tweet= Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: "index" ,notice: 'tweetを削除しました'

  end

  private

  def tweet_params
  params.require(:tweet).permit(:text).merge(user_id:current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniApp</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Compiled and minified CSS -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

   <!-- Compiled and minified JavaScript -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
   <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
 
  </head>

  <body>
  <%= render 'layouts/notifications' %>
   
   <nav class="#66bb6a green lighten-1">
  <div class="nav-wrapper">
    <a href="/tweets" class="brand-logo center-align">Miniapp</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
    <% if user_signed_in? %>
      <li><%=link_to "投稿",new_tweet_path,method: :get %></li>
      <li><%=link_to "ログアウト",destroy_user_session_path,method: :delete %></li>
    <% else %>
      <li><%=link_to "ログイン",new_user_session_path%></li>
      <li><%=link_to "新規登録",new_user_registration_path%></li>
    <% end %>
    </ul>
  </div>
</nav>


    <%= yield %>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="original-box">
    <div class="col s12 m6 z-depth-2">
      <div class="card #c8e6c9 green lighten-4">
        <div class="card-content white-text">
          <%=tweet.text%>
        </div>
          <div class="card-action">
          <% if user_signed_in? %>     
            <%=link_to "編集","tweets/#{tweet.id}/edit",method: :get%>
            <%=link_to "削除","tweets/#{tweet.id}",method: :delete%>        
          <% else %>
            </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/tweets/create.html.erb
<div class = "contens row">
     <div class="success">
      <h3>
        投稿が完了しました。
      </h3>


      <img src="./LGTM.jpg" width="40%" height="30%">
      <a class="btn" href="/tweets">投稿へ戻る</a>
     </div>
  </div>

app/views/tweets/edit.html.erb
<%=form_for @tweet do |f| %>
<%=f.label :tweet%>
<%= f.text_field :text %>
<%= f.submit :SEND %>
<% end %>

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>
 
        
</head>
<body>


<%= render @tweets %>

<%= paginate @tweets %>

<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/tweets/new.html.erb
<%=form_for @tweet do |f|%>
<%=f.label :tweet%>
<%=f.text_field :text %>
<%=f.submit%>
<% end %>